connectors:
  matrix:
    # Required
    mxid: '@bot_clarex:bot.parsi.ai'
    password: '12345'
    rooms:
      'main': '#NLP-test1:bot.parsi.ai'

    # Optional
    homeserver: 'https://bot.parsi.ai'
    nick: 'Great Bot'
    device_id: 'opsdroid'
    enable_encryption: True

databases:
  sqlite:
    path: './new_regex/message_patterns.db'
    table: 'message_patterns'

skills:
  accept_invite:
    path: 'skills/accept_invite.py'
  join_room:
    path: 'skills/join_room.py'
  help:
    path: 'skills/help.py'
  regex_generator:
    path: 'skills/regex_generator.py'
  info:
    path: 'skills/info.py'
  add_regex:
    path: 'skills/add_regex.py'
  check_with_new_regexes:
    path: 'skills/check_with_new_regexes.py'
  check_message_with_regex:
    path: 'skills/check_message_with_regex.py'