connectors:
  matrix:
    # Required
    mxid: '@bot_clarex:bot.parsi.ai'
    password: '12345'
    rooms:
      'main': '#NLP-test:bot.parsi.ai'

    # Optional
    homeserver: "https://bot.parsi.ai"
    nick: "Bot"
    device_id: "opsdroid"
    enable_encryption: True

skills:
  test:
    path: 'skills/test.py'
  accept_invite:
    path: 'skills/accept_invite.py'
  join_room:
    path: 'skills/join_room.py'
  help:
    path: 'skills/help.py'
  regex_generator1:
    path: 'skills/regex_generator.py'